networks:
  inception:
    name: ${COMPOSE_PROJECT_NAME}

secrets:
  mariadb_user_password:
    file: ../secrets/mariadb_user_password.txt

  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt

  wordpress_user_password:
    file: ../secrets/wordpress_user_password.txt

  wordpress_root_password:
    file: ../secrets/wordpress_root_password.txt

  vsftpd_user_password:
    file: ../secrets/vsftpd_user_password.txt

services:
  mariadb:
    container_name: mariadb
    expose:
      - ${MARIADB_PORT}
    healthcheck:
      test: [
        "CMD-SHELL", 
        "mariadb-admin ping \
        -h$MARIADB_HOST \
        -P$MARIADB_PORT \
        -u$MARIADB_USER \
        -p$$(cat /run/secrets/mariadb_user_password) \
        --silent"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - mariadb_user_password
      - mariadb_root_password
    restart: on-failure

  wordpress:
    container_name: wordpress
    expose:
      - ${WORDPRESS_PORT}
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      LOCAL_USER: ${LOCAL_USER}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_ROOT: ${WORDPRESS_ROOT}
      WORDPRESS_ROOT_EMAIL: ${WORDPRESS_ROOT_EMAIL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    secrets:
      - mariadb_user_password
      - wordpress_user_password
      - wordpress_root_password
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    container_name: nginx
    expose:
      - ${NGINX_PORT}
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    environment:
      NGINX_PORT: ${NGINX_PORT}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_HOST: ${WORDPRESS_HOST}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      ADMINER_HOST: ${ADMINER_HOST}
      ADMINER_PORT: ${ADMINER_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - wordpress_data:/var/www/html/wordpress:ro
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_started
      static_site:
        condition: service_started

  redis:
    container_name: redis
    expose:
      - ${REDIS_PORT}
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
      args:
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
        - ${COMPOSE_PROJECT_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure

  vsftpd:
    container_name: vsftpd
    expose:
      - ${VSFTPD_PORT}
      - ${VSFTPD_PORT_START_RANGE}-${VSFTPD_PORT_END_RANGE}
    build:
      context: ./requirements/bonus/vsftpd
      dockerfile: Dockerfile
      args:
        VSFTPD_USER: ${VSFTPD_USER}
    environment:
      VSFTPD_PORT: ${VSFTPD_PORT}
      VSFTPD_USER: ${VSFTPD_USER}
      VSFTPD_PORT_START_RANGE: ${VSFTPD_PORT_START_RANGE}
      VSFTPD_PORT_END_RANGE: ${VSFTPD_PORT_END_RANGE}
    secrets:
      - vsftpd_user_password
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${VSFTPD_PORT}:${VSFTPD_PORT}
      - ${VSFTPD_PORT_START_RANGE}-${VSFTPD_PORT_END_RANGE}:${VSFTPD_PORT_START_RANGE}-${VSFTPD_PORT_END_RANGE}
    volumes:
      - wordpress_data:/home/${VSFTPD_USER}/vsftpd/wordpress
    restart: on-failure
    depends_on:
      - wordpress

  static_site:
    container_name: static_site
    expose:
      - ${STATIC_SITE_PORT}
    build:
      context: ./requirements/bonus/static_site
      dockerfile: Dockerfile
      args:
        STATIC_SITE_PORT: ${STATIC_SITE_PORT}
    environment:
      STATIC_SITE_PORT: ${STATIC_SITE_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${STATIC_SITE_PORT}:${STATIC_SITE_PORT}
    restart: on-failure

  adminer:
    container_name: adminer
    expose:
      - ${ADMINER_PORT}
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
      args:
        ADMINER_HOST: ${ADMINER_HOST}
        ADMINER_PORT: ${ADMINER_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      - wordpress

  cadvisor:
    container_name: cadvisor
    expose:
      - ${CADVISOR_PORT}
    build:
      context: ./requirements/bonus/cadvisor
      dockerfile: Dockerfile
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    ports:
      - ${CADVISOR_PORT}:${CADVISOR_PORT}
    restart: on-failure
    depends_on:
      - mariadb
      - wordpress
      - nginx
      - redis
      - vsftpd
      - static_site
      - adminer

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOCAL_USER}/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOCAL_USER}/data/wordpress
      o: bind
