networks:
  inception:
    name: ${COMPOSE_PROJECT_NAME}

secrets:
  mariadb_user_password:
    file: secrets/mariadb_user_password.txt

  mariadb_root_password:
    file: secrets/mariadb_root_password.txt

  wordpress_user_password:
    file: secrets/wordpress_user_password.txt

  wordpress_root_password:
    file: secrets/wordpress_root_password.txt

  vsftpd_password:
    file: secrets/vsftpd_password.txt

services:
  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    expose:
      - ${MARIADB_PORT}
    healthcheck:
      test: [
        "CMD-SHELL", 
        "mariadb-admin ping \
        -h$MARIADB_HOST \
        -P$MARIADB_PORT \
        -u$MARIADB_USER \
        -p$$(cat /run/secrets/mariadb_user_password) \
        --silent"
      ]
      interval: 5s
      timeout: 30s
      retries: 5
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - mariadb_user_password
      - mariadb_root_password
    restart: on-failure

  wordpress:
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    expose:
      - ${WORDPRESS_PORT}
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      LOCAL_USER: ${LOCAL_USER}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      WORDPRESS_USER: ${WORDPRESS_USER}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
      WORDPRESS_ROOT: ${WORDPRESS_ROOT}
      WORDPRESS_ROOT_EMAIL: ${WORDPRESS_ROOT_EMAIL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    secrets:
      - mariadb_user_password
      - wordpress_user_password
      - wordpress_root_password
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    expose:
      - ${NGINX_PORT}
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    environment:
      NGINX_PORT: ${NGINX_PORT}
      WORDPRESS_DOMAIN: ${WORDPRESS_DOMAIN}
      WORDPRESS_HOST: ${WORDPRESS_HOST}
      WORDPRESS_PORT: ${WORDPRESS_PORT}
      ADMINER_HOST: ${ADMINER_HOST}
      ADMINER_PORT: ${ADMINER_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
     - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - wordpress_data:/var/www/html/wordpress:ro
    restart: on-failure
    depends_on:
      - wordpress

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    expose:
      - ${REDIS_PORT}
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
      args:
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
    networks:
        - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      - wordpress

  vsftpd:
    container_name: ${COMPOSE_PROJECT_NAME}_vsftpd
    expose:
      - ${VSFTPD_PORT}
      - ${VSFTPD_PORT_RANGE}
    build:
      context: ./requirements/vsftpd
      dockerfile: Dockerfile
      args:
        SHARED_GROUP: ${SHARED_GROUP}
    environment:
      VSFTPD_PORT: ${VSFTPD_PORT}
      VSFTPD_USER: ${VSFTPD_USER}
    secrets:
      - vsftpd_password
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${VSFTPD_PORT}:${VSFTPD_PORT}
      - ${VSFTPD_PORT_RANGE}:${VSFTPD_PORT_RANGE}
    volumes:
      - wordpress_data:/home/${VSFTPD_USER}/vsftpd/wordpress
    restart: on-failure
    depends_on:
      - wordpress

  static_site:
    container_name: ${COMPOSE_PROJECT_NAME}_static_site
    expose:
      - ${STATIC_SITE_PORT}
    build:
      context: ./requirements/static_site
      dockerfile: Dockerfile
      args:
        STATIC_SITE_PORT: ${STATIC_SITE_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    ports:
      - ${STATIC_SITE_PORT}:${STATIC_SITE_PORT}
    restart: on-failure

  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    expose:
      - ${ADMINER_PORT}
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
      args:
        ADMINER_HOST: ${ADMINER_HOST}
        ADMINER_PORT: ${ADMINER_PORT}
    networks:
      - ${COMPOSE_PROJECT_NAME}
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: on-failure
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOCAL_USER}/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${LOCAL_USER}/data/wordpress
      o: bind
